name: fastfood
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  sentry_flutter: ^8.13.0
  auto_route: ^8.1.3
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  hive: ^2.2.3
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  oktoast: ^3.4.0
  pinput: ^5.0.0
  pretty_dio_logger: ^1.4.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  location: ^8.0.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  flutter_google_maps_webservices: ^1.1.1
  google_fonts: ^6.2.1
  pull_to_refresh: ^2.0.0
  carousel_slider: ^5.1.1
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  google_sign_in: ^6.2.1
  firebase_messaging: ^15.2.10
  firebase_database: ^11.3.10
  cloud_firestore: ^5.6.11
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.6

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.3
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  image: assets/images/app_icon.png
  image_dark: assets/images/app_icon.png
  android_12:
    image: assets/images/app_icon.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/app_icon.png
    icon_background_color_dark: "#121212"
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/2x/
    - assets/icons/3x/
