// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIz3jtWvJj2OVqGKdsDo2FT1E4Vnaz-QQ',
    appId: '1:727332831743:android:806e1f6cdf3c65cb89a7ca',
    messagingSenderId: '727332831743',
    projectId: 'fastfood-a0d93',
    databaseURL: 'https://fastfood-a0d93-default-rtdb.firebaseio.com',
    storageBucket: 'fastfood-a0d93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGlvkH84RbK1ZaCt2TCUO9La2N2obnNuo',
    appId: '1:727332831743:ios:8ceb8937347b831989a7ca',
    messagingSenderId: '727332831743',
    projectId: 'fastfood-a0d93',
    databaseURL: 'https://fastfood-a0d93-default-rtdb.firebaseio.com',
    storageBucket: 'fastfood-a0d93.firebasestorage.app',
    androidClientId: '727332831743-1o12kfhpjrrrtupkmejor7u6v37pii8n.apps.googleusercontent.com',
    iosClientId: '727332831743-g1t17tp5v7i72cft1blm8vt2dkspu5p8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastfood',
  );

}